sudo: required

os:
  - linux

language: c
dist: xenial

matrix:
  include:
    # Build and test against the master (stable) and devel branches of Nim
    # Build and test using both gcc and clang
    - os: linux
      env: CHANNEL=stable
      compiler: gcc

    - os: linux
      env: CHANNEL=devel
      compiler: gcc

cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"

addons:
  apt:
     packages:
       - libcairo2
       - libcairo2-dev
       - imagemagick

install:
  - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - sh init.sh -y
  - export PATH=$HOME/.nimble/bin:$PATH
  - nimble refresh -y
  - choosenim $CHANNEL
  - nimble install ntangle -y

script:
  # limit our stack size to avoid regressing after PR #36 w/o noticing
  - ulimit -s 1024
  - nimble install -y
  - nimble -y fulltest
  - nimble -y testCI
